start_timed:
  name: Start Timed
  description: Start a valve with automatic shutoff after specified minutes
  fields:
    name:
      name: Valve Name
      description: Name of the valve to control
      required: true
      example: "Water Valve 1"
      selector:
        text:
    minutes:
      name: Minutes
      description: Number of minutes to run
      required: true
      example: 30
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min

start_litres:
  name: Start Litres
  description: Start a valve until target litres reached
  fields:
    name:
      name: Valve Name
      description: Name of the valve to control
      required: true
      example: "Water Valve 1"
      selector:
        text:
    litres:
      name: Litres
      description: Target litres to dispense
      required: true
      example: 50
      selector:
        number:
          min: 1
          max: 10000
          unit_of_measurement: L
    hard_timeout_min:
      name: Hard Timeout (minutes)
      description: Maximum runtime failsafe (optional)
      required: false
      example: 120
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: min

stop:
  name: Stop
  description: Manually stop a valve
  fields:
    name:
      name: Valve Name
      description: Name of the valve to stop
      required: true
      example: "Water Valve 1"
      selector:
        text:

reset_total:
  name: Reset Total
  description: Reset the total litres counter for a valve
  fields:
    name:
      name: Valve Name
      description: Name of the valve to reset
      required: true
      example: "Water Valve 1"
      selector:
        text:
