start_timed:
  name: Start timed run
  description: Start valve for a number of minutes.
  fields:
    valve:
      description: Friendly name from Zigbee2MQTT (e.g. "Water Valve 3")
      example: Water Valve 3
    minutes:
      description: Minutes to run
      example: 30
      selector: { number: { min: 1, max: 600, unit_of_measurement: "min"} }

start_liters:
  name: Start litres run
  description: Start valve and stop when the specified litres have flowed.
  fields:
    valve:
      description: Friendly name (Zigbee2MQTT)
    liters:
      description: Litres target
      selector: { number: { min: 0.1, max: 500.0, step: 0.1, unit_of_measurement: "L"} }

stop:
  name: Stop valve
  fields:
    valve:
      description: Friendly name

reset_totals:
  name: Reset totals
  description: Reset total litres and total minutes counters.
  fields:
    valve:
      description: Friendly name
