start_timed:
  name: Start timed session
  description: Turn the valve on for a fixed number of minutes.
  fields:
    valve:
      name: Valve (Zigbee2MQTT friendly name)
      example: Water Valve 3
      required: true
      selector:
        text:
    minutes:
      name: Minutes
      example: 30
      required: true
      selector:
        number:
          min: 0
          step: 1
start_liters:
  name: Start liters session
  description: Turn the valve on until the specified liters have flowed (based on flow readings).
  fields:
    valve:
      name: Valve (Zigbee2MQTT friendly name)
      example: Water Valve 3
      required: true
      selector:
        text:
    liters:
      name: Liters
      example: 60
      required: true
      selector:
        number:
          min: 0
          step: 0.1
reset_totals:
  name: Reset totals
  description: Reset total liters and total minutes. If valve is omitted, resets all valves.
  fields:
    valve:
      name: Valve (optional)
      required: false
      selector:
        text:
